# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vhalla <vhalla@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/10 13:37:56 by osergeev          #+#    #+#              #
#    Updated: 2021/06/13 10:36:14 by vhalla           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-2
SRC = 

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:
	rm -rf *.o

fclean:	clean
	rm -rf $(NAME)

re:	fclean all